services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./tmp_storage:/app/tmp_storage
    env_file:
      - .env
    environment:
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    networks:
      - deep_critic_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - deep_critic_network

networks:
  deep_critic_network:
    name: deep_critic_network