version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # For development - auto-reload with code changes
    env_file:
      - .env
    environment:
      - DEBUG=true
      # Add other environment variables as needed

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # For development - auto-reload with code changes
    depends_on:
      - backend

networks:
  default:
    name: deep_critic_network# Docker Compose configuration for DeepCritic
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/deepcritic
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-dummy-key-for-development}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy-key-for-development}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-dummy-key-for-development}
    restart: unless-stopped
    # Simple command that uses a sleep instead of netcat
    command: >
      bash -c "
        npm run dev
      "