# Simple Docker Compose for DeepCritic
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:5000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-dummy-key-for-development}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy-key-for-development}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-dummy-key-for-development}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped